version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - /app/node_modules  # Убедитесь, что это необходимо для вашего приложения
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./frontend  # Укажите правильный путь к вашему веб-приложению
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env 
    volumes:
      - ./frontend:/app  # Убедитесь, что монтируете правильный каталог
      - /app/node_modules
    command: pnpm dev

volumes:
  postgres_data: