
services:
  traefik:
    image: traefik:v3.0
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      # - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=PathPrefix("/backend")
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.routers.app.priority=10
      - traefik.http.services.app.loadbalancer.server.port=8000
    networks:
      - traefik
      - default
    ports:
      - "8000:8000"  # Expose app on port 8000
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.75'

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '0.5'

  web:
    build: ./frontend
    env_file:
      - ./frontend/.env
    command: pnpm start
    ports:
      - "3000:3000"
    environment:
    - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=PathPrefix("/frontend")
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.routers.web.priority=5
      - traefik.http.services.web.loadbalancer.server.port=3000
    networks:
      - traefik
      - default
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

volumes:
  postgres_data:
  node_modules_cache:
  nextjs_cache:

networks:
  traefik:
    driver: bridge
