"""New ProductModel structure

Revision ID: 03d092d6f56f
Revises: 39e8f1bdd49f
Create Date: 2025-04-27 22:48:09.455036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d092d6f56f'
down_revision: Union[str, None] = '39e8f1bdd49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('products', sa.Column('title', sa.String(), nullable=False))
    #op.add_column('products', sa.Column('description_html', sa.String(), nullable=True))
    #op.add_column('products', sa.Column('handle', sa.String(), nullable=True))
    #op.add_column('products', sa.Column('variants', sa.JSON(), nullable=True))
    #op.add_column('products', sa.Column('options', sa.JSON(), nullable=True))
    #op.add_column('products', sa.Column('price_range', sa.JSON(), nullable=True))
    #op.add_column('products', sa.Column('featured_image', sa.JSON(), nullable=True))
    #op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    #op.add_column('products', sa.Column('available_for_sale', sa.Boolean(), nullable=True))
    #op.add_column('products', sa.Column('seo', sa.JSON(), nullable=True))
    #op.add_column('products', sa.Column('tags', sa.JSON(), nullable=True))
    #op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    #op.create_unique_constraint(None, 'products', ['handle'])
    #op.drop_column('products', 'price')
    #op.drop_column('products', 'image')
    #op.drop_column('products', 'color')
    #op.drop_column('products', 'name')
    #op.drop_column('products', 'size')
    #op.drop_column('products', 'delivery')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('delivery', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'seo')
    op.drop_column('products', 'available_for_sale')
    op.drop_column('products', 'images')
    op.drop_column('products', 'featured_image')
    op.drop_column('products', 'price_range')
    op.drop_column('products', 'options')
    op.drop_column('products', 'variants')
    op.drop_column('products', 'handle')
    op.drop_column('products', 'description_html')
    op.drop_column('products', 'title')
    # ### end Alembic commands ###
