"""add_shipping_and_payment_fields_to_orders

Revision ID: 601d0af560f3
Revises: aa066267d424
Create Date: 2025-08-30 13:29:15.636943

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "601d0af560f3"
down_revision: str | None = "aa066267d424"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("email", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("shipping_address", sa.JSON(), nullable=True))
    op.add_column("orders", sa.Column("payment_method", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "payment_method")
    op.drop_column("orders", "shipping_address")
    op.drop_column("orders", "email")
    # ### end Alembic commands ###
