"""New OrderModel

Revision ID: aa066267d424
Revises: 787219884b02
Create Date: 2025-06-29 15:37:19.061852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa066267d424'
down_revision: Union[str, None] = '787219884b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('carts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('carts_products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('carts_products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('order_products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order_products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'created_at')
    op.drop_column('products', 'created_at')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('order_products', 'updated_at')
    op.drop_column('order_products', 'created_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('carts_products', 'updated_at')
    op.drop_column('carts_products', 'created_at')
    op.drop_column('carts', 'updated_at')
    op.drop_column('carts', 'created_at')
    # ### end Alembic commands ###
